/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projecta

import library.Library

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val library = Library()
    println(library.message)
}
