/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package projectb

import library.Library

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val myLib = Library()
    println(myLib.message)
}
